services:
  - type: web
    name: raftlabs-backend
    env: node
    plan: free
    buildCommand: npm ci --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npx prisma db seed && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: raftlabs-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
      - key: STATUS_PREPARING_DELAY
        value: "60000"
      - key: STATUS_DELIVERY_DELAY
        value: "60000"
      - key: STATUS_DELIVERED_DELAY
        value: "60000"
databases:
  - name: raftlabs-db
    plan: free
    databaseName: raftlabs
    user: raftlabs
