export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MENU_ITEM_NOT_FOUND = 'MENU_ITEM_NOT_FOUND',
  MENU_ITEM_UNAVAILABLE = 'MENU_ITEM_UNAVAILABLE',
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  INVALID_ORDER_STATUS_TRANSITION = 'INVALID_ORDER_STATUS_TRANSITION',
  ORDER_CANNOT_BE_MODIFIED = 'ORDER_CANNOT_BE_MODIFIED',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  DATABASE_ERROR = 'DATABASE_ERROR',
}
